create table if not exists public.email_export_usage (
  id bigint generated by default as identity primary key,
  firebase_uid text not null,
  export_date date not null,
  recipient_email text not null,
  status text not null check (status in ('pending', 'sent')),
  provider_message_id text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (firebase_uid, export_date)
);

alter table public.email_export_usage enable row level security;
